// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable
{
    public IWebDriver driver { get; private set; }
    public IDictionary<String, Object> vars { get; private set; }
    public IJavaScriptExecutor js { get; private set; }
    public SuiteTests()
    {
        driver = new ChromeDriver(@"C:\\Users\\Rohan\\Downloads\\chromedriver-win64\\chromedriver-win64");
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<String, Object>();
    }
    public void Dispose()
    {
        driver.Quit();
    }
    [Fact]
    public void LoginWithValidCrendential()
    {
        driver.Navigate().GoToUrl("https://localhost:7158/");
        driver.Manage().Window.Size = new System.Drawing.Size(1296, 736);
        driver.FindElement(By.Id("genreId")).Click();
        {
            var dropdown = driver.FindElement(By.Id("genreId"));
            dropdown.FindElement(By.XPath("//option[. = 'Romance Noval']")).Click();
        }
        driver.FindElement(By.Id("genreId")).Click();
        {
            var dropdown = driver.FindElement(By.Id("genreId"));
            dropdown.FindElement(By.XPath("//option[. = 'Horror']")).Click();
        }
        driver.FindElement(By.Id("sterm")).Click();
        driver.FindElement(By.CssSelector(".btn:nth-child(1)")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(4) .btn")).Click();
        driver.FindElement(By.Id("Input_Email")).Click();
        driver.FindElement(By.Id("Input_Email")).SendKeys("admin@gmail.com");
        driver.FindElement(By.Id("Input_Password")).Click();
        driver.FindElement(By.Id("Input_Password")).SendKeys("Admin@123");
        driver.FindElement(By.Id("login-submit")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(12) .btn")).Click();
        driver.FindElement(By.CssSelector(".bi")).Click();
        driver.FindElement(By.LinkText("Checkout")).Click();
        driver.FindElement(By.Id("Name")).Click();
        driver.FindElement(By.Id("Name")).SendKeys("rohan");
        {
            var element = driver.FindElement(By.CssSelector(".py-2:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".py-2:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".py-2:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector("form:nth-child(3)")).Click();
        driver.FindElement(By.Id("Email")).SendKeys("rohanjundare@gmail.com");
        {
            var element = driver.FindElement(By.Id("Address"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.Id("Address"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.Id("Address"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector("form:nth-child(3)")).Click();
        driver.FindElement(By.Id("MobileNumber")).SendKeys("8007790700");
        {
            var element = driver.FindElement(By.Id("Address"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.Id("Address"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.Id("Address"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.Id("Address")).Click();
        driver.FindElement(By.Id("Address")).SendKeys("dnl");
        driver.FindElement(By.Id("PaymentMethod")).Click();
        {
            var dropdown = driver.FindElement(By.Id("PaymentMethod"));
            dropdown.FindElement(By.XPath("//option[. = 'COD']")).Click();
        }
        driver.FindElement(By.CssSelector(".btn-info")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector("html")).Click();
        driver.Close();
    }
}
